name: Deploy to Google Cloud Instance

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

   
    - name: Deploy to Compute Engine Instance
      run: |
        # Define variables
        INSTANCE_NAME="demo-poc"
        ZONE="us-central1-b"  # Replace with your instance's zone
        SSH_USER="your-email"  # Replace with the user for the instance
        SSH_KEY="${{ secrets.GCP_SSH_PRIVATE_KEY }}"  # Add private SSH key to secrets
        DEPLOY_SCRIPT="Script.sh"  # Script to run on the instance

        # Write SSH key to a file
        echo "$GCP_SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        

        # Generate public key (if missing)
        ssh-keygen -y -f private_key > private_key.pub

        # Ensure public key is added to the instance metadata or project metadata
        ssh -i private_key your-email@34.135.4.248

        
        # Run the deployment script on the instance
        echo "Running the deployment script on the instance..."
        gcloud compute ssh "$SSH_USER@$INSTANCE_NAME" \
          --zone "$ZONE" \
          --ssh-key-file=private_key \
          --command "cd /home/$SSH_USER/app && chmod +x $DEPLOY_SCRIPT && ./Script.sh" --verbosity=debug
