name: Deploy to Google Cloud

on:
  push:
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Set up SSH key
      run: |
        # Define variables
        INSTANCE_NAME="demo-poc"
        ZONE="us-central1-b"  # Replace with your instance's zone
        SSH_USER="your-email"  # Replace with the user for the instance
        DEPLOY_SCRIPT="Script.sh"  # Script to run on the instance
        
        # Write SSH private key to a file
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key
        chmod 600 private_key
        
        # Verify SSH key format (optional, but ensures it's valid)
        ssh-keygen -l -f private_key || exit 1
        
        # Generate public key (if missing)
        ssh-keygen -y -f private_key > private_key.pub
        
    - name: Authenticate with Google Cloud
      run: |
        # Authenticate the Google Cloud SDK with the service account
        gcloud auth activate-service-account --key-file="${{ secrets.GCP_CREDENTIALS_JSON }}"
        
    - name: Transfer files to Google Cloud instance
      run: |
        echo "Copying files to the instance..."
        gcloud compute scp --zone "$ZONE" \
          --ssh-key-file=private_key \
          --recurse . "$SSH_USER@$INSTANCE_NAME:/home/$SSH_USER/app" --verbosity=debug

    - name: Run deployment script on the instance
      run: |
        echo "Running the deployment script on the instance..."
        gcloud compute ssh "$SSH_USER@$INSTANCE_NAME" \
          --zone "$ZONE" \
          --ssh-key-file=private_key \
          --command "cd /home/$SSH_USER/app && chmod +x $DEPLOY_SCRIPT && ./$DEPLOY_SCRIPT" --verbosity=debug

    - name: Clean up private key file
      run: |
        # Clean up the private key file after the deployment
        rm private_key private_key.pub
