name: Deploy to Google Cloud Instance

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies and fix libcrypto error
      run: |
        # Install required packages
        sudo apt-get update -y
        sudo apt-get install openssh-client wget gnupg -y
        # Add Docker GPG key
        wget -qO- https://get.docker.com/gpg | sudo apt-key add -
        
        # Fix libcrypto error by setting an explicit OpenSSL version (if needed)
        export OPENSSL_CONF=/etc/ssl/openssl.cnf
        
        # Start ssh-agent manually and add the SSH key
        eval $(ssh-agent -s)
        
        # Add SSH key to agent without using stdin, avoiding libcrypto error
        mkdir -p ~/.ssh
        echo "$GCP_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-add ~/.ssh/id_rsa

        # Prepare SSH configuration
        touch ~/.ssh/config
        touch ~/.ssh/known_hosts
        chmod -R 400 ~/.ssh
        # Add the instance to known hosts (replace <ip> with actual IP)
        ssh-keyscan 34.135.4.248 >> ~/.ssh/known_hosts

    - name: Deploy to Compute Engine Instance
      run: |
        # Define variables
        INSTANCE_NAME="demo-poc"
        ZONE="us-central1-b"  # Replace with your instance's zone
        SSH_USER="your-email"  # Replace with the user for the instance
        SSH_KEY="${{ secrets.GCP_SSH_PRIVATE_KEY }}"  # Add private SSH key to secrets
        DEPLOY_SCRIPT="Script.sh"  # Script to run on the instance

        # Write SSH key to a file
        echo "$GCP_SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key

        # Generate public key (if missing)
        ssh-keygen -y -f private_key > private_key.pub

        # Ensure public key is added to the instance metadata or project metadata
        ssh -i private_key "$SSH_USER@34.135.4.248"

        # Run the deployment script on the instance
        echo "Running the deployment script on the instance..."
        gcloud compute ssh "$SSH_USER@$INSTANCE_NAME" \
          --zone "$ZONE" \
          --ssh-key-file=private_key \
          --command "cd /home/$SSH_USER/app && chmod +x $DEPLOY_SCRIPT && ./$DEPLOY_SCRIPT" --verbosity=debug
